server:
  port: ${PORT:2020}

swagger:
  title: "Authentication Service API"
  description: "API documentation for authentication service"

spring:
  profiles:
    active: ${SPRING_PROFILE:local}
  application:
    name: auth-service
  management:
    endpoints:
      web:
        exposure:
          include: health, info, refresh

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
  api-docs:
    path: /v3/api-docs
