spring:
  data:
    mongodb:
      uri: mongodb+srv://javaServiceUser:J1KOomWoId30LtuK@cluster0.7xfaek8.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: ThunkNestDB
  neo4j:
    uri: neo4j+s://a7083374.databases.neo4j.io
    authentication:
      username: neo4j
      password: cVdXhk479zP8DG8E1XEIgQd0urZt53JQTBB9w7IqC_4
