spring:
  data:
    mongodb:
      uri: mongodb+srv://thunknestAdmin:4gAI74ZvKD1o3eeg@thunknestdb.wa6jo.mongodb.net/
      database: thunkNestDB
  neo4j:
    uri: neo4j+s://101fc5ab.databases.neo4j.io
    authentication:
      username: neo4j
      password: MdIfQnts-BwwPmm7gz44yyLEByaCv5dZ2tyrNxR6YV8
