spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/thunkNestDB
      database: thunkNestDB
  neo4j:
    uri: neo4j+s://101fc5ab.databases.neo4j.io
    authentication:
      username: neo4j
      password: cVdXhk479zP8DG8E1XEIgQd0urZt53JQTBB9w7IqC_4
