spring:
  data:
    mongodb:
      uri: mongodb+srv://javaServiceUser:J1KOomWoId30LtuK@cluster0.7xfaek8.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: ThunkNestDB
  neo4j:
    uri: neo4j+s://101fc5ab.databases.neo4j.io
    authentication:
      username: neo4j
      password: MdIfQnts-BwwPmm7gz44yyLEByaCv5dZ2tyrNxR6YV8