server:
  port: ${PORT:2024}

swagger:
  title: "Vote Service API"
  description: "API documentation for vote service"

spring:
  profiles:
    active: ${SPRING_PROFILE:local}
  application:
    name: vote-service
  management:
    endpoints:
      web:
        exposure:
          include: health, info, refresh
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VHOST:/}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
  api-docs:
    path: /v3/api-docs
